export const ADD_USER = "ADD_USER"
export const LOGIN_USER = "LOGIN_USER"
export const ERROR_MESSAGE = "ERROR_MESSAGE"
export const LOG_OUT = "LOG_OUT"
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const VIEW_PRODUCTS = "VIEW_PRODUCTS"
export const VIEW_PRODUCT = "VIEW_PRODUCT"
export const VIEW_PRODUCT_TYPES = "VIEW_PRODUCT_TYPES"